# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-18 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('codigo_postal', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('media', models.FileField(blank=True, null=True, upload_to='myfolder/')),
                ('tipo_de_carga', models.CharField(blank=True, max_length=120, null=True)),
                ('lugar_de_origen', models.CharField(blank=True, max_length=120, null=True)),
                ('lugar_de_destino', models.CharField(blank=True, max_length=120, null=True)),
                ('volumen_de_la_carga', models.IntegerField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
